name: FibCalc
on:
  push:
    branches: [ master ]

jobs:
  build_and_push_backend:
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: backend
    
    steps:
      - uses: actions/checkout@v3

      - name: Buildx set-up
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKER_HUB_USERNAME}}
          password: ${{secrets.DOCKER_HUB_ACCESS_TOKEN}}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          cache-from: type=registry,ref=persi52/zadanie1-frontend:latest
          cache-to: type=registry,ref=persi52/zadanie1-frontend:latest,mode=max
          platforms: linux/arm/v7,linux/arm64/v8,linux/amd64
          context: backend
          push: true
          tags: |
            ${{secrets.DOCKER_HUB_USERNAME}}/zadanie1-chmura:latest
      
      # #Przenies cache'a
      # - name: Move cache
      #   run: |
      #     rm -rf /tmp/.buildx-cache
      #     mv /tmp/.buildx-cache-new /tmp/.buildx-cache

  build_and_push_frontend:
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: my-app
    
    steps:
      - uses: actions/checkout@v3

      - name: Buildx set-up
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKER_HUB_USERNAME}}
          password: ${{secrets.DOCKER_HUB_ACCESS_TOKEN}}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          cache-from: type=registry,ref=persi52/zadanie1-frontend:latest
          cache-to: type=registry,ref=persi52/zadanie1-frontend:latest,mode=max
          platforms: linux/arm/v7,linux/arm64/v8,linux/amd64
          context: my-app
          push: true
          tags: |
            ${{secrets.DOCKER_HUB_USERNAME}}/zadanie1-chmura:latest
      
      # #Przenies cache'a
      # - name: Move cache
      #   run: |
      #     rm -rf /tmp/.buildx-cache
      #     mv /tmp/.buildx-cache-new /tmp/.buildx-cache
